version: '2.3'

services:
  cs848w20:
    build:
      context: src/
    volumes:
      - ./src/:/src
    working_dir: /src
    command: tail -f /dev/null

  cs848w20_magellan:
    build:
      context: magellan/
    volumes:
      - ./magellan/:/magellan
      - ./datasets/:/datasets
    working_dir: /root
    command: tail -f /dev/null